[package]
name = "obshtml_module_lib"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "*"
yaml-rust = "0.4"
regex = "1"
lazy_static = "1.4.0"
thiserror = "1.0"
chrono = "0.4.26"
